/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client";
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import * as dat from "dat.gui";
import * as THREE from "three";
 

let gui;
export default function Streets(props) {
    const streets = useRef()
    const geometryBaseColor = {
      color: "#7292a0",
   
    }
  
    const uniforms= { 
      color: { value: new THREE.Color(geometryBaseColor.hex) }
    }
   

    
    const init = async () => {
        const dat = await import('dat.gui')
        if (!gui) {
           gui = new dat.GUI()
           const colorFolder = gui.addFolder("Streets") 
           const streetsColor = colorFolder.addColor(geometryBaseColor, "color")
         streetsColor.onChange((value) => {
             streets.current.material.color = new THREE.Color(value)
           })
       
        
       
           return () => {
             gui.destroy()
           }
           // ... rest of the three.js code
        }
     }
    useEffect(() => {
        init()
   
    
    }, []);

    return (
        <mesh
        scale={100}
        rotation={[-Math.PI / 2, 0, 0]}
        position={[0.0, -0.5, 0.0]}
        ref={streets}
       
      >
        {/* <meshStandardMaterial color={"#e0e0e0"} />   */}
        {/* <meshStandardMaterial color={"grey"} /> */}
        <meshStandardMaterial color={"#7292a0"} />

        <planeGeometry></planeGeometry>
      </mesh>
    );
}

 
